param(
    [string]$InstallDir = "C:\abaqus-mcp",
    [string]$PythonCommand = "python",
    [switch]$SkipPythonPackage
)

$ErrorActionPreference = "Stop"

$RepoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$SourceDir = Join-Path $RepoRoot "abaqus-mcp"

if (-not (Test-Path -LiteralPath $SourceDir)) {
    throw "Source directory not found: $SourceDir"
}

New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null

robocopy $SourceDir $InstallDir /E `
    /XD .git .claude commands results jobs screenshots scripts temp userprofile __pycache__ `
    /XF *.pyc mcp.log status.json status.json.tmp stop.flag | Out-Null
if ($LASTEXITCODE -gt 7) {
    throw "robocopy failed with exit code $LASTEXITCODE"
}

if (-not $SkipPythonPackage) {
    & $PythonCommand -m pip install --user mcp
}

$PluginSource = Join-Path $InstallDir "abaqus_plugins\mcp_control"
$PluginRoot = Join-Path $env:USERPROFILE "abaqus_plugins"
$PluginTarget = Join-Path $PluginRoot "mcp_control"
New-Item -ItemType Directory -Force -Path $PluginRoot | Out-Null
Copy-Item -Recurse -Force -LiteralPath $PluginSource -Destination $PluginTarget

$EnvPath = Join-Path $env:USERPROFILE "abaqus_v6.env"
if (Test-Path -LiteralPath $EnvPath) {
    $Stamp = Get-Date -Format "yyyyMMdd-HHmmss"
    Copy-Item -LiteralPath $EnvPath -Destination "$EnvPath.bak-before-abaqus-mcp-$Stamp"
}

$InstallDirForPython = $InstallDir.TrimEnd("\")
$EnvText = @"
# Abaqus Environment Configuration
# Auto-load Abaqus MCP Plugin on startup.
# Generated by Abaqus 6.14 MCP Suite.

import io
import os
import sys

def onCaeStartup():
    """Called when Abaqus/CAE starts"""
    mcp_home = r'$InstallDirForPython'
    os.environ['ABAQUS_MCP_HOME'] = mcp_home
    mcp_plugin = os.path.join(mcp_home, 'abaqus_mcp_plugin.py')

    if os.path.exists(mcp_plugin):
        import __main__
        with io.open(mcp_plugin, 'r', encoding='utf-8') as f:
            code = f.read()
        exec(compile(code, mcp_plugin, 'exec'), __main__.__dict__)
        print('Abaqus MCP auto-loaded from: ' + mcp_plugin)
    else:
        print('Abaqus MCP plugin not found: ' + mcp_plugin)
"@

Set-Content -LiteralPath $EnvPath -Value $EnvText -Encoding ASCII

$McpServerPath = Join-Path $InstallDirForPython "mcp_server.py"

Write-Host ""
Write-Host "Installed Abaqus MCP to: $InstallDirForPython"
Write-Host "Abaqus startup file: $EnvPath"
Write-Host "Abaqus GUI plugin: $PluginTarget"
Write-Host ""
Write-Host "In Abaqus/CAE, run:"
Write-Host "  execfile(r'$InstallDirForPython\abaqus_mcp_plugin.py')"
Write-Host "  mcp_status()"
Write-Host "  mcp_loop()"
Write-Host ""
Write-Host "Codex config.toml snippet:"
Write-Host "[mcp_servers.abaqus-mcp-server]"
Write-Host "enabled = true"
Write-Host "command = `"$PythonCommand`""
Write-Host "args = [`"-c`", `"import os, runpy; os.environ['ABAQUS_MCP_HOME'] = r'$InstallDirForPython'; runpy.run_path(r'$McpServerPath', run_name='__main__')`"]"
Write-Host "startup_timeout_sec = 15"
Write-Host "tool_timeout_sec = 700"

